name: anchore-analysis

env:
  DOCKER_IMAGE_NAME: webdevsvc/portainer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  anchore-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          load: true
          push: false
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Perform Anchore analysis
        uses: anchore/scan-action@v2.0.4
        with:
          acs-report-enable: true
          image: ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Upload Anchore report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
